export const ID_TYPES = [
  { value: 'nin', label: 'National Identification Number (NIN)' },
  { value: 'bvn', label: 'Bank Verification Number (BVN)' },
  { value: 'passport', label: 'International Passport' },
  { value: 'drivers_license', label: "Driver's License" },
]

export const NIGERIAN_STATES = [
  { value: 'abia', label: 'Abia' },
  { value: 'adamawa', label: 'Adamawa' },
  { value: 'akwa_ibom', label: 'Akwa Ibom' },
  { value: 'anambra', label: 'Anambra' },
  { value: 'bauchi', label: 'Bauchi' },
  { value: 'bayelsa', label: 'Bayelsa' },
  { value: 'benue', label: 'Benue' },
  { value: 'borno', label: 'Borno' },
  { value: 'cross_river', label: 'Cross River' },
  { value: 'delta', label: 'Delta' },
  { value: 'ebonyi', label: 'Ebonyi' },
  { value: 'edo', label: 'Edo' },
  { value: 'ekiti', label: 'Ekiti' },
  { value: 'enugu', label: 'Enugu' },
  { value: 'fct', label: 'FCT — Abuja' },
  { value: 'gombe', label: 'Gombe' },
  { value: 'imo', label: 'Imo' },
  { value: 'jigawa', label: 'Jigawa' },
  { value: 'kaduna', label: 'Kaduna' },
  { value: 'kano', label: 'Kano' },
  { value: 'katsina', label: 'Katsina' },
  { value: 'kebbi', label: 'Kebbi' },
  { value: 'kogi', label: 'Kogi' },
  { value: 'kwara', label: 'Kwara' },
  { value: 'lagos', label: 'Lagos' },
  { value: 'nasarawa', label: 'Nasarawa' },
  { value: 'niger', label: 'Niger' },
  { value: 'ogun', label: 'Ogun' },
  { value: 'ondo', label: 'Ondo' },
  { value: 'osun', label: 'Osun' },
  { value: 'oyo', label: 'Oyo' },
  { value: 'plateau', label: 'Plateau' },
  { value: 'rivers', label: 'Rivers' },
  { value: 'sokoto', label: 'Sokoto' },
  { value: 'taraba', label: 'Taraba' },
  { value: 'yobe', label: 'Yobe' },
  { value: 'zamfara', label: 'Zamfara' },
]

export const LGAS_BY_STATE: Record<string, { value: string; label: string }[]> = {
  abia: [
    { value: 'aba_north', label: 'Aba North' },
    { value: 'aba_south', label: 'Aba South' },
    { value: 'arochukwu', label: 'Arochukwu' },
    { value: 'bende', label: 'Bende' },
    { value: 'ikwuano', label: 'Ikwuano' },
    { value: 'isiala_ngwa_north', label: 'Isiala Ngwa North' },
    { value: 'isiala_ngwa_south', label: 'Isiala Ngwa South' },
    { value: 'isuikwuato', label: 'Isuikwuato' },
    { value: 'obi_ngwa', label: 'Obi Ngwa' },
    { value: 'ohafia', label: 'Ohafia' },
    { value: 'osisioma', label: 'Osisioma' },
    { value: 'ugwunagbo', label: 'Ugwunagbo' },
    { value: 'ukwa_east', label: 'Ukwa East' },
    { value: 'ukwa_west', label: 'Ukwa West' },
    { value: 'umuahia_north', label: 'Umuahia North' },
    { value: 'umuahia_south', label: 'Umuahia South' },
    { value: 'umu_nneochi', label: 'Umu Nneochi' },
  ],
  adamawa: [
    { value: 'demsa', label: 'Demsa' },
    { value: 'fufore', label: 'Fufore' },
    { value: 'ganye', label: 'Ganye' },
    { value: 'girei', label: 'Girei' },
    { value: 'gombi', label: 'Gombi' },
    { value: 'guyuk', label: 'Guyuk' },
    { value: 'hong', label: 'Hong' },
    { value: 'jada', label: 'Jada' },
    { value: 'lamurde', label: 'Lamurde' },
    { value: 'madagali', label: 'Madagali' },
    { value: 'maiha', label: 'Maiha' },
    { value: 'mayo_belwa', label: 'Mayo Belwa' },
    { value: 'michika', label: 'Michika' },
    { value: 'mubi_north', label: 'Mubi North' },
    { value: 'mubi_south', label: 'Mubi South' },
    { value: 'numan', label: 'Numan' },
    { value: 'shelleng', label: 'Shelleng' },
    { value: 'song', label: 'Song' },
    { value: 'toungo', label: 'Toungo' },
    { value: 'yola_north', label: 'Yola North' },
    { value: 'yola_south', label: 'Yola South' },
  ],
  akwa_ibom: [
    { value: 'abak', label: 'Abak' },
    { value: 'eastern_obolo', label: 'Eastern Obolo' },
    { value: 'eket', label: 'Eket' },
    { value: 'esit_eket', label: 'Esit Eket' },
    { value: 'essien_udim', label: 'Essien Udim' },
    { value: 'etim_ekpo', label: 'Etim Ekpo' },
    { value: 'etinan', label: 'Etinan' },
    { value: 'ibeno', label: 'Ibeno' },
    { value: 'ibesikpo_asutan', label: 'Ibesikpo Asutan' },
    { value: 'ibiono_ibom', label: 'Ibiono Ibom' },
    { value: 'ika', label: 'Ika' },
    { value: 'ikono', label: 'Ikono' },
    { value: 'ikot_abasi', label: 'Ikot Abasi' },
    { value: 'ikot_ekpene', label: 'Ikot Ekpene' },
    { value: 'ini', label: 'Ini' },
    { value: 'itu', label: 'Itu' },
    { value: 'mbo', label: 'Mbo' },
    { value: 'mkpat_enin', label: 'Mkpat Enin' },
    { value: 'nsit_atai', label: 'Nsit Atai' },
    { value: 'nsit_ibom', label: 'Nsit Ibom' },
    { value: 'nsit_ubium', label: 'Nsit Ubium' },
    { value: 'obot_akara', label: 'Obot Akara' },
    { value: 'okobo', label: 'Okobo' },
    { value: 'onna', label: 'Onna' },
    { value: 'oron', label: 'Oron' },
    { value: 'oruk_anam', label: 'Oruk Anam' },
    { value: 'udung_uko', label: 'Udung Uko' },
    { value: 'ukanafun', label: 'Ukanafun' },
    { value: 'uruan', label: 'Uruan' },
    { value: 'urue_offong_oruko', label: 'Urue Offong/Oruko' },
    { value: 'uyo', label: 'Uyo' },
  ],
  anambra: [
    { value: 'aguata', label: 'Aguata' },
    { value: 'anambra_east', label: 'Anambra East' },
    { value: 'anambra_west', label: 'Anambra West' },
    { value: 'anaocha', label: 'Anaocha' },
    { value: 'awka_north', label: 'Awka North' },
    { value: 'awka_south', label: 'Awka South' },
    { value: 'ayamelum', label: 'Ayamelum' },
    { value: 'dunukofia', label: 'Dunukofia' },
    { value: 'ekwusigo', label: 'Ekwusigo' },
    { value: 'idemili_north', label: 'Idemili North' },
    { value: 'idemili_south', label: 'Idemili South' },
    { value: 'ihiala', label: 'Ihiala' },
    { value: 'njikoka', label: 'Njikoka' },
    { value: 'nnewi_north', label: 'Nnewi North' },
    { value: 'nnewi_south', label: 'Nnewi South' },
    { value: 'ogbaru', label: 'Ogbaru' },
    { value: 'onitsha_north', label: 'Onitsha North' },
    { value: 'onitsha_south', label: 'Onitsha South' },
    { value: 'orumba_north', label: 'Orumba North' },
    { value: 'orumba_south', label: 'Orumba South' },
    { value: 'oyi', label: 'Oyi' },
  ],
  bauchi: [
    { value: 'alkaleri', label: 'Alkaleri' },
    { value: 'bauchi', label: 'Bauchi' },
    { value: 'bogoro', label: 'Bogoro' },
    { value: 'damban', label: 'Damban' },
    { value: 'darazo', label: 'Darazo' },
    { value: 'dass', label: 'Dass' },
    { value: 'gamawa', label: 'Gamawa' },
    { value: 'ganjuwa', label: 'Ganjuwa' },
    { value: 'giade', label: 'Giade' },
    { value: 'itas_gadau', label: 'Itas/Gadau' },
    { value: 'jama_are', label: "Jama'are" },
    { value: 'katagum', label: 'Katagum' },
    { value: 'kirfi', label: 'Kirfi' },
    { value: 'misau', label: 'Misau' },
    { value: 'ningi', label: 'Ningi' },
    { value: 'shira', label: 'Shira' },
    { value: 'tafawa_balewa', label: 'Tafawa Balewa' },
    { value: 'toro', label: 'Toro' },
    { value: 'warji', label: 'Warji' },
    { value: 'zaki', label: 'Zaki' },
  ],
  bayelsa: [
    { value: 'brass', label: 'Brass' },
    { value: 'ekeremor', label: 'Ekeremor' },
    { value: 'kolokuma_opokuma', label: 'Kolokuma/Opokuma' },
    { value: 'nembe', label: 'Nembe' },
    { value: 'ogbia', label: 'Ogbia' },
    { value: 'sagbama', label: 'Sagbama' },
    { value: 'southern_ijaw', label: 'Southern Ijaw' },
    { value: 'yenagoa', label: 'Yenagoa' },
  ],
  benue: [
    { value: 'ado', label: 'Ado' },
    { value: 'agatu', label: 'Agatu' },
    { value: 'apa', label: 'Apa' },
    { value: 'buruku', label: 'Buruku' },
    { value: 'gboko', label: 'Gboko' },
    { value: 'guma', label: 'Guma' },
    { value: 'gwer_east', label: 'Gwer East' },
    { value: 'gwer_west', label: 'Gwer West' },
    { value: 'katsina_ala', label: 'Katsina-Ala' },
    { value: 'konshisha', label: 'Konshisha' },
    { value: 'kwande', label: 'Kwande' },
    { value: 'logo', label: 'Logo' },
    { value: 'makurdi', label: 'Makurdi' },
    { value: 'obi', label: 'Obi' },
    { value: 'ogbadibo', label: 'Ogbadibo' },
    { value: 'ohimini', label: 'Ohimini' },
    { value: 'oju', label: 'Oju' },
    { value: 'okpokwu', label: 'Okpokwu' },
    { value: 'otukpo', label: 'Otukpo' },
    { value: 'tarka', label: 'Tarka' },
    { value: 'ukum', label: 'Ukum' },
    { value: 'ushongo', label: 'Ushongo' },
    { value: 'vandeikya', label: 'Vandeikya' },
  ],
  borno: [
    { value: 'abadam', label: 'Abadam' },
    { value: 'askira_uba', label: 'Askira/Uba' },
    { value: 'bama', label: 'Bama' },
    { value: 'bayo', label: 'Bayo' },
    { value: 'biu', label: 'Biu' },
    { value: 'chibok', label: 'Chibok' },
    { value: 'damboa', label: 'Damboa' },
    { value: 'dikwa', label: 'Dikwa' },
    { value: 'gubio', label: 'Gubio' },
    { value: 'guzamala', label: 'Guzamala' },
    { value: 'gwoza', label: 'Gwoza' },
    { value: 'hawul', label: 'Hawul' },
    { value: 'jere', label: 'Jere' },
    { value: 'kaga', label: 'Kaga' },
    { value: 'kala_balge', label: 'Kala/Balge' },
    { value: 'konduga', label: 'Konduga' },
    { value: 'kukawa', label: 'Kukawa' },
    { value: 'kwaya_kusar', label: 'Kwaya Kusar' },
    { value: 'mafa', label: 'Mafa' },
    { value: 'magumeri', label: 'Magumeri' },
    { value: 'maiduguri', label: 'Maiduguri' },
    { value: 'marte', label: 'Marte' },
    { value: 'mobbar', label: 'Mobbar' },
    { value: 'monguno', label: 'Monguno' },
    { value: 'ngala', label: 'Ngala' },
    { value: 'nganzai', label: 'Nganzai' },
    { value: 'shani', label: 'Shani' },
  ],
  cross_river: [
    { value: 'abi', label: 'Abi' },
    { value: 'akamkpa', label: 'Akamkpa' },
    { value: 'akpabuyo', label: 'Akpabuyo' },
    { value: 'bakassi', label: 'Bakassi' },
    { value: 'bekwarra', label: 'Bekwarra' },
    { value: 'biase', label: 'Biase' },
    { value: 'boki', label: 'Boki' },
    { value: 'calabar_municipal', label: 'Calabar Municipal' },
    { value: 'calabar_south', label: 'Calabar South' },
    { value: 'etung', label: 'Etung' },
    { value: 'ikom', label: 'Ikom' },
    { value: 'obanliku', label: 'Obanliku' },
    { value: 'obubra', label: 'Obubra' },
    { value: 'obudu', label: 'Obudu' },
    { value: 'odukpani', label: 'Odukpani' },
    { value: 'ogoja', label: 'Ogoja' },
    { value: 'yakuur', label: 'Yakuur' },
    { value: 'yala', label: 'Yala' },
  ],
  delta: [
    { value: 'aniocha_north', label: 'Aniocha North' },
    { value: 'aniocha_south', label: 'Aniocha South' },
    { value: 'bomadi', label: 'Bomadi' },
    { value: 'burutu', label: 'Burutu' },
    { value: 'ethiope_east', label: 'Ethiope East' },
    { value: 'ethiope_west', label: 'Ethiope West' },
    { value: 'ika_north_east', label: 'Ika North East' },
    { value: 'ika_south', label: 'Ika South' },
    { value: 'isoko_north', label: 'Isoko North' },
    { value: 'isoko_south', label: 'Isoko South' },
    { value: 'ndokwa_east', label: 'Ndokwa East' },
    { value: 'ndokwa_west', label: 'Ndokwa West' },
    { value: 'okpe', label: 'Okpe' },
    { value: 'oshimili_north', label: 'Oshimili North' },
    { value: 'oshimili_south', label: 'Oshimili South' },
    { value: 'patani', label: 'Patani' },
    { value: 'sapele', label: 'Sapele' },
    { value: 'udu', label: 'Udu' },
    { value: 'ughelli_north', label: 'Ughelli North' },
    { value: 'ughelli_south', label: 'Ughelli South' },
    { value: 'ukwuani', label: 'Ukwuani' },
    { value: 'uvwie', label: 'Uvwie' },
    { value: 'warri_north', label: 'Warri North' },
    { value: 'warri_south', label: 'Warri South' },
    { value: 'warri_south_west', label: 'Warri South West' },
  ],
  ebonyi: [
    { value: 'abakaliki', label: 'Abakaliki' },
    { value: 'afikpo_north', label: 'Afikpo North' },
    { value: 'afikpo_south', label: 'Afikpo South' },
    { value: 'ebonyi', label: 'Ebonyi' },
    { value: 'ezza_north', label: 'Ezza North' },
    { value: 'ezza_south', label: 'Ezza South' },
    { value: 'ikwo', label: 'Ikwo' },
    { value: 'ishielu', label: 'Ishielu' },
    { value: 'ivo', label: 'Ivo' },
    { value: 'izzi', label: 'Izzi' },
    { value: 'ohaozara', label: 'Ohaozara' },
    { value: 'ohaukwu', label: 'Ohaukwu' },
    { value: 'onicha', label: 'Onicha' },
  ],
  edo: [
    { value: 'akoko_edo', label: 'Akoko-Edo' },
    { value: 'egor', label: 'Egor' },
    { value: 'esan_central', label: 'Esan Central' },
    { value: 'esan_north_east', label: 'Esan North-East' },
    { value: 'esan_south_east', label: 'Esan South-East' },
    { value: 'esan_west', label: 'Esan West' },
    { value: 'etsako_central', label: 'Etsako Central' },
    { value: 'etsako_east', label: 'Etsako East' },
    { value: 'etsako_west', label: 'Etsako West' },
    { value: 'igueben', label: 'Igueben' },
    { value: 'ikpoba_okha', label: 'Ikpoba-Okha' },
    { value: 'orhionmwon', label: 'Orhionmwon' },
    { value: 'oredo', label: 'Oredo' },
    { value: 'ovia_north_east', label: 'Ovia North-East' },
    { value: 'ovia_south_west', label: 'Ovia South-West' },
    { value: 'owan_east', label: 'Owan East' },
    { value: 'owan_west', label: 'Owan West' },
    { value: 'uhunmwonde', label: 'Uhunmwonde' },
  ],
  ekiti: [
    { value: 'ado_ekiti', label: 'Ado Ekiti' },
    { value: 'efon', label: 'Efon' },
    { value: 'ekiti_east', label: 'Ekiti East' },
    { value: 'ekiti_south_west', label: 'Ekiti South-West' },
    { value: 'ekiti_west', label: 'Ekiti West' },
    { value: 'emure', label: 'Emure' },
    { value: 'gbonyin', label: 'Gbonyin' },
    { value: 'ido_osi', label: 'Ido/Osi' },
    { value: 'ijero', label: 'Ijero' },
    { value: 'ikere', label: 'Ikere' },
    { value: 'ikole', label: 'Ikole' },
    { value: 'ilejemeje', label: 'Ilejemeje' },
    { value: 'irepodun_ifelodun', label: 'Irepodun/Ifelodun' },
    { value: 'ise_orun', label: 'Ise/Orun' },
    { value: 'moba', label: 'Moba' },
    { value: 'oye', label: 'Oye' },
  ],
  enugu: [
    { value: 'aninri', label: 'Aninri' },
    { value: 'awgu', label: 'Awgu' },
    { value: 'enugu_east', label: 'Enugu East' },
    { value: 'enugu_north', label: 'Enugu North' },
    { value: 'enugu_south', label: 'Enugu South' },
    { value: 'ezeagu', label: 'Ezeagu' },
    { value: 'igbo_etiti', label: 'Igbo Etiti' },
    { value: 'igbo_eze_north', label: 'Igbo Eze North' },
    { value: 'igbo_eze_south', label: 'Igbo Eze South' },
    { value: 'isi_uzo', label: 'Isi Uzo' },
    { value: 'nkanu_east', label: 'Nkanu East' },
    { value: 'nkanu_west', label: 'Nkanu West' },
    { value: 'nsukka', label: 'Nsukka' },
    { value: 'oji_river', label: 'Oji River' },
    { value: 'udenu', label: 'Udenu' },
    { value: 'udi', label: 'Udi' },
    { value: 'uzo_uwani', label: 'Uzo Uwani' },
  ],
  fct: [
    { value: 'abaji', label: 'Abaji' },
    { value: 'bwari', label: 'Bwari' },
    { value: 'gwagwalada', label: 'Gwagwalada' },
    { value: 'kuje', label: 'Kuje' },
    { value: 'kwali', label: 'Kwali' },
    { value: 'municipal_area_council', label: 'Municipal Area Council' },
  ],
  gombe: [
    { value: 'akko', label: 'Akko' },
    { value: 'balanga', label: 'Balanga' },
    { value: 'billiri', label: 'Billiri' },
    { value: 'dukku', label: 'Dukku' },
    { value: 'funakaye', label: 'Funakaye' },
    { value: 'gombe', label: 'Gombe' },
    { value: 'kaltungo', label: 'Kaltungo' },
    { value: 'kwami', label: 'Kwami' },
    { value: 'nafada', label: 'Nafada' },
    { value: 'shomgom', label: 'Shomgom' },
    { value: 'yamaltu_deba', label: 'Yamaltu/Deba' },
  ],
  imo: [
    { value: 'aboh_mbaise', label: 'Aboh Mbaise' },
    { value: 'ahiazu_mbaise', label: 'Ahiazu Mbaise' },
    { value: 'ehime_mbano', label: 'Ehime Mbano' },
    { value: 'ezinihitte', label: 'Ezinihitte' },
    { value: 'ideato_north', label: 'Ideato North' },
    { value: 'ideato_south', label: 'Ideato South' },
    { value: 'ihitte_uboma', label: 'Ihitte/Uboma' },
    { value: 'ikeduru', label: 'Ikeduru' },
    { value: 'isiala_mbano', label: 'Isiala Mbano' },
    { value: 'isu', label: 'Isu' },
    { value: 'mbaitoli', label: 'Mbaitoli' },
    { value: 'ngor_okpala', label: 'Ngor Okpala' },
    { value: 'njaba', label: 'Njaba' },
    { value: 'nkwerre', label: 'Nkwerre' },
    { value: 'nwangele', label: 'Nwangele' },
    { value: 'obowo', label: 'Obowo' },
    { value: 'oguta', label: 'Oguta' },
    { value: 'ohaji_egbema', label: 'Ohaji/Egbema' },
    { value: 'okigwe', label: 'Okigwe' },
    { value: 'orlu', label: 'Orlu' },
    { value: 'orsu', label: 'Orsu' },
    { value: 'oru_east', label: 'Oru East' },
    { value: 'oru_west', label: 'Oru West' },
    { value: 'owerri_municipal', label: 'Owerri Municipal' },
    { value: 'owerri_north', label: 'Owerri North' },
    { value: 'owerri_west', label: 'Owerri West' },
    { value: 'unuimo', label: 'Unuimo' },
  ],
  jigawa: [
    { value: 'auyo', label: 'Auyo' },
    { value: 'babura', label: 'Babura' },
    { value: 'biriniwa', label: 'Biriniwa' },
    { value: 'birnin_kudu', label: 'Birnin Kudu' },
    { value: 'buji', label: 'Buji' },
    { value: 'dutse', label: 'Dutse' },
    { value: 'gagarawa', label: 'Gagarawa' },
    { value: 'garki', label: 'Garki' },
    { value: 'gumel', label: 'Gumel' },
    { value: 'guri', label: 'Guri' },
    { value: 'gwaram', label: 'Gwaram' },
    { value: 'gwiwa', label: 'Gwiwa' },
    { value: 'hadejia', label: 'Hadejia' },
    { value: 'jahun', label: 'Jahun' },
    { value: 'kafin_hausa', label: 'Kafin Hausa' },
    { value: 'kaugama', label: 'Kaugama' },
    { value: 'kazaure', label: 'Kazaure' },
    { value: 'kiri_kasamma', label: 'Kiri Kasamma' },
    { value: 'kiyawa', label: 'Kiyawa' },
    { value: 'maigatari', label: 'Maigatari' },
    { value: 'malam_madori', label: 'Malam Madori' },
    { value: 'miga', label: 'Miga' },
    { value: 'ringim', label: 'Ringim' },
    { value: 'roni', label: 'Roni' },
    { value: 'sule_tankarkar', label: 'Sule Tankarkar' },
    { value: 'taura', label: 'Taura' },
    { value: 'yankwashi', label: 'Yankwashi' },
  ],
  kaduna: [
    { value: 'birnin_gwari', label: 'Birnin Gwari' },
    { value: 'chikun', label: 'Chikun' },
    { value: 'giwa', label: 'Giwa' },
    { value: 'igabi', label: 'Igabi' },
    { value: 'ikara', label: 'Ikara' },
    { value: 'jaba', label: 'Jaba' },
    { value: 'jema_a', label: "Jema'a" },
    { value: 'kachia', label: 'Kachia' },
    { value: 'kaduna_north', label: 'Kaduna North' },
    { value: 'kaduna_south', label: 'Kaduna South' },
    { value: 'kagarko', label: 'Kagarko' },
    { value: 'kajuru', label: 'Kajuru' },
    { value: 'kaura', label: 'Kaura' },
    { value: 'kauru', label: 'Kauru' },
    { value: 'kubau', label: 'Kubau' },
    { value: 'kudan', label: 'Kudan' },
    { value: 'lere', label: 'Lere' },
    { value: 'makarfi', label: 'Makarfi' },
    { value: 'sabon_gari', label: 'Sabon Gari' },
    { value: 'sanga', label: 'Sanga' },
    { value: 'soba', label: 'Soba' },
    { value: 'zangon_kataf', label: 'Zangon Kataf' },
    { value: 'zaria', label: 'Zaria' },
  ],
  kano: [
    { value: 'ajingi', label: 'Ajingi' },
    { value: 'albasu', label: 'Albasu' },
    { value: 'bagwai', label: 'Bagwai' },
    { value: 'bebeji', label: 'Bebeji' },
    { value: 'bichi', label: 'Bichi' },
    { value: 'bunkure', label: 'Bunkure' },
    { value: 'dala', label: 'Dala' },
    { value: 'dambatta', label: 'Dambatta' },
    { value: 'dawakin_kudu', label: 'Dawakin Kudu' },
    { value: 'dawakin_tofa', label: 'Dawakin Tofa' },
    { value: 'doguwa', label: 'Doguwa' },
    { value: 'fagge', label: 'Fagge' },
    { value: 'gabasawa', label: 'Gabasawa' },
    { value: 'garko', label: 'Garko' },
    { value: 'garum_mallam', label: 'Garum Mallam' },
    { value: 'gaya', label: 'Gaya' },
    { value: 'gezawa', label: 'Gezawa' },
    { value: 'gwale', label: 'Gwale' },
    { value: 'gwarzo', label: 'Gwarzo' },
    { value: 'kabo', label: 'Kabo' },
    { value: 'kano_municipal', label: 'Kano Municipal' },
    { value: 'karaye', label: 'Karaye' },
    { value: 'kibiya', label: 'Kibiya' },
    { value: 'kiru', label: 'Kiru' },
    { value: 'kumbotso', label: 'Kumbotso' },
    { value: 'kunchi', label: 'Kunchi' },
    { value: 'kura', label: 'Kura' },
    { value: 'madobi', label: 'Madobi' },
    { value: 'makoda', label: 'Makoda' },
    { value: 'minjibir', label: 'Minjibir' },
    { value: 'nasarawa', label: 'Nasarawa' },
    { value: 'rano', label: 'Rano' },
    { value: 'rimin_gado', label: 'Rimin Gado' },
    { value: 'rogo', label: 'Rogo' },
    { value: 'shanono', label: 'Shanono' },
    { value: 'sumaila', label: 'Sumaila' },
    { value: 'takai', label: 'Takai' },
    { value: 'tarauni', label: 'Tarauni' },
    { value: 'tofa', label: 'Tofa' },
    { value: 'tsanyawa', label: 'Tsanyawa' },
    { value: 'tudun_wada', label: 'Tudun Wada' },
    { value: 'ungogo', label: 'Ungogo' },
    { value: 'warawa', label: 'Warawa' },
    { value: 'wudil', label: 'Wudil' },
  ],
  katsina: [
    { value: 'bakori', label: 'Bakori' },
    { value: 'batagarawa', label: 'Batagarawa' },
    { value: 'batsari', label: 'Batsari' },
    { value: 'baure', label: 'Baure' },
    { value: 'bindawa', label: 'Bindawa' },
    { value: 'charanchi', label: 'Charanchi' },
    { value: 'dandume', label: 'Dandume' },
    { value: 'danja', label: 'Danja' },
    { value: 'dan_musa', label: 'Dan Musa' },
    { value: 'daura', label: 'Daura' },
    { value: 'dutsi', label: 'Dutsi' },
    { value: 'dutsin_ma', label: 'Dutsin Ma' },
    { value: 'faskari', label: 'Faskari' },
    { value: 'funtua', label: 'Funtua' },
    { value: 'ingawa', label: 'Ingawa' },
    { value: 'jibia', label: 'Jibia' },
    { value: 'kafur', label: 'Kafur' },
    { value: 'kaita', label: 'Kaita' },
    { value: 'kankara', label: 'Kankara' },
    { value: 'kankia', label: 'Kankia' },
    { value: 'katsina', label: 'Katsina' },
    { value: 'kurfi', label: 'Kurfi' },
    { value: 'kusada', label: 'Kusada' },
    { value: 'mai_adua', label: "Mai'Adua" },
    { value: 'malumfashi', label: 'Malumfashi' },
    { value: 'mani', label: 'Mani' },
    { value: 'mashi', label: 'Mashi' },
    { value: 'matazu', label: 'Matazu' },
    { value: 'musawa', label: 'Musawa' },
    { value: 'rimi', label: 'Rimi' },
    { value: 'sabuwa', label: 'Sabuwa' },
    { value: 'safana', label: 'Safana' },
    { value: 'sandamu', label: 'Sandamu' },
    { value: 'zango', label: 'Zango' },
  ],
  kebbi: [
    { value: 'aleiro', label: 'Aleiro' },
    { value: 'arewa_dandi', label: 'Arewa Dandi' },
    { value: 'argungu', label: 'Argungu' },
    { value: 'augie', label: 'Augie' },
    { value: 'bagudo', label: 'Bagudo' },
    { value: 'birnin_kebbi', label: 'Birnin Kebbi' },
    { value: 'bunza', label: 'Bunza' },
    { value: 'dandi', label: 'Dandi' },
    { value: 'fakai', label: 'Fakai' },
    { value: 'gwandu', label: 'Gwandu' },
    { value: 'jega', label: 'Jega' },
    { value: 'kalgo', label: 'Kalgo' },
    { value: 'koko_besse', label: 'Koko/Besse' },
    { value: 'maiyama', label: 'Maiyama' },
    { value: 'ngaski', label: 'Ngaski' },
    { value: 'sakaba', label: 'Sakaba' },
    { value: 'shanga', label: 'Shanga' },
    { value: 'suru', label: 'Suru' },
    { value: 'wasagu_danko', label: 'Wasagu/Danko' },
    { value: 'yauri', label: 'Yauri' },
    { value: 'zuru', label: 'Zuru' },
  ],
  kogi: [
    { value: 'adavi', label: 'Adavi' },
    { value: 'ajaokuta', label: 'Ajaokuta' },
    { value: 'ankpa', label: 'Ankpa' },
    { value: 'bassa', label: 'Bassa' },
    { value: 'dekina', label: 'Dekina' },
    { value: 'ibaji', label: 'Ibaji' },
    { value: 'idah', label: 'Idah' },
    { value: 'igalamela_odolu', label: 'Igalamela Odolu' },
    { value: 'ijumu', label: 'Ijumu' },
    { value: 'kabba_bunu', label: 'Kabba/Bunu' },
    { value: 'kogi', label: 'Kogi' },
    { value: 'lokoja', label: 'Lokoja' },
    { value: 'mopa_muro', label: 'Mopa Muro' },
    { value: 'ofu', label: 'Ofu' },
    { value: 'ogori_magongo', label: 'Ogori/Magongo' },
    { value: 'okehi', label: 'Okehi' },
    { value: 'okene', label: 'Okene' },
    { value: 'olamaboro', label: 'Olamaboro' },
    { value: 'omala', label: 'Omala' },
    { value: 'yagba_east', label: 'Yagba East' },
    { value: 'yagba_west', label: 'Yagba West' },
  ],
  kwara: [
    { value: 'asa', label: 'Asa' },
    { value: 'baruten', label: 'Baruten' },
    { value: 'edu', label: 'Edu' },
    { value: 'ekiti_kwara', label: 'Ekiti' },
    { value: 'ifelodun', label: 'Ifelodun' },
    { value: 'ilorin_east', label: 'Ilorin East' },
    { value: 'ilorin_south', label: 'Ilorin South' },
    { value: 'ilorin_west', label: 'Ilorin West' },
    { value: 'irepodun', label: 'Irepodun' },
    { value: 'isin', label: 'Isin' },
    { value: 'kaiama', label: 'Kaiama' },
    { value: 'moro', label: 'Moro' },
    { value: 'offa', label: 'Offa' },
    { value: 'oke_ero', label: 'Oke Ero' },
    { value: 'oyun', label: 'Oyun' },
    { value: 'pategi', label: 'Pategi' },
  ],
  lagos: [
    { value: 'agege', label: 'Agege' },
    { value: 'ajeromi_ifelodun', label: 'Ajeromi-Ifelodun' },
    { value: 'alimosho', label: 'Alimosho' },
    { value: 'amuwo_odofin', label: 'Amuwo-Odofin' },
    { value: 'apapa', label: 'Apapa' },
    { value: 'badagry', label: 'Badagry' },
    { value: 'epe', label: 'Epe' },
    { value: 'eti_osa', label: 'Eti-Osa' },
    { value: 'ibeju_lekki', label: 'Ibeju-Lekki' },
    { value: 'ifako_ijaiye', label: 'Ifako-Ijaiye' },
    { value: 'ikeja', label: 'Ikeja' },
    { value: 'ikorodu', label: 'Ikorodu' },
    { value: 'kosofe', label: 'Kosofe' },
    { value: 'lagos_island', label: 'Lagos Island' },
    { value: 'lagos_mainland', label: 'Lagos Mainland' },
    { value: 'mushin', label: 'Mushin' },
    { value: 'ojo', label: 'Ojo' },
    { value: 'oshodi_isolo', label: 'Oshodi-Isolo' },
    { value: 'shomolu', label: 'Shomolu' },
    { value: 'surulere', label: 'Surulere' },
  ],
  nasarawa: [
    { value: 'akwanga', label: 'Akwanga' },
    { value: 'awe', label: 'Awe' },
    { value: 'doma', label: 'Doma' },
    { value: 'karu', label: 'Karu' },
    { value: 'keana', label: 'Keana' },
    { value: 'keffi', label: 'Keffi' },
    { value: 'kokona', label: 'Kokona' },
    { value: 'lafia', label: 'Lafia' },
    { value: 'nasarawa', label: 'Nasarawa' },
    { value: 'nasarawa_egon', label: 'Nasarawa Egon' },
    { value: 'obi', label: 'Obi' },
    { value: 'toto', label: 'Toto' },
    { value: 'wamba', label: 'Wamba' },
  ],
  niger: [
    { value: 'agaie', label: 'Agaie' },
    { value: 'agwara', label: 'Agwara' },
    { value: 'bida', label: 'Bida' },
    { value: 'borgu', label: 'Borgu' },
    { value: 'bosso', label: 'Bosso' },
    { value: 'chanchaga', label: 'Chanchaga' },
    { value: 'edati', label: 'Edati' },
    { value: 'gbako', label: 'Gbako' },
    { value: 'gurara', label: 'Gurara' },
    { value: 'katcha', label: 'Katcha' },
    { value: 'kontagora', label: 'Kontagora' },
    { value: 'lapai', label: 'Lapai' },
    { value: 'lavun', label: 'Lavun' },
    { value: 'magama', label: 'Magama' },
    { value: 'mariga', label: 'Mariga' },
    { value: 'mashegu', label: 'Mashegu' },
    { value: 'mokwa', label: 'Mokwa' },
    { value: 'moya', label: 'Moya' },
    { value: 'paikoro', label: 'Paikoro' },
    { value: 'rafi', label: 'Rafi' },
    { value: 'rijau', label: 'Rijau' },
    { value: 'shiroro', label: 'Shiroro' },
    { value: 'suleja', label: 'Suleja' },
    { value: 'tafa', label: 'Tafa' },
    { value: 'wushishi', label: 'Wushishi' },
  ],
  ogun: [
    { value: 'abeokuta_north', label: 'Abeokuta North' },
    { value: 'abeokuta_south', label: 'Abeokuta South' },
    { value: 'ado_odo_ota', label: 'Ado-Odo/Ota' },
    { value: 'ewekoro', label: 'Ewekoro' },
    { value: 'ifo', label: 'Ifo' },
    { value: 'ijebu_east', label: 'Ijebu East' },
    { value: 'ijebu_north', label: 'Ijebu North' },
    { value: 'ijebu_north_east', label: 'Ijebu North East' },
    { value: 'ijebu_ode', label: 'Ijebu Ode' },
    { value: 'ikenne', label: 'Ikenne' },
    { value: 'imeko_afon', label: 'Imeko Afon' },
    { value: 'ipokia', label: 'Ipokia' },
    { value: 'obafemi_owode', label: 'Obafemi Owode' },
    { value: 'odeda', label: 'Odeda' },
    { value: 'odogbolu', label: 'Odogbolu' },
    { value: 'ogun_waterside', label: 'Ogun Waterside' },
    { value: 'remo_north', label: 'Remo North' },
    { value: 'sagamu', label: 'Sagamu' },
    { value: 'yewa_north', label: 'Yewa North' },
    { value: 'yewa_south', label: 'Yewa South' },
  ],
  ondo: [
    { value: 'akoko_north_east', label: 'Akoko North-East' },
    { value: 'akoko_north_west', label: 'Akoko North-West' },
    { value: 'akoko_south_east', label: 'Akoko South-East' },
    { value: 'akoko_south_west', label: 'Akoko South-West' },
    { value: 'akure_north', label: 'Akure North' },
    { value: 'akure_south', label: 'Akure South' },
    { value: 'ese_odo', label: 'Ese Odo' },
    { value: 'idanre', label: 'Idanre' },
    { value: 'ifedore', label: 'Ifedore' },
    { value: 'ilaje', label: 'Ilaje' },
    { value: 'ile_oluji_okeigbo', label: 'Ile Oluji/Okeigbo' },
    { value: 'irele', label: 'Irele' },
    { value: 'odigbo', label: 'Odigbo' },
    { value: 'okitipupa', label: 'Okitipupa' },
    { value: 'ondo_east', label: 'Ondo East' },
    { value: 'ondo_west', label: 'Ondo West' },
    { value: 'ose', label: 'Ose' },
    { value: 'owo', label: 'Owo' },
  ],
  osun: [
    { value: 'aiyedade', label: 'Aiyedade' },
    { value: 'aiyedire', label: 'Aiyedire' },
    { value: 'atakumosa_east', label: 'Atakumosa East' },
    { value: 'atakumosa_west', label: 'Atakumosa West' },
    { value: 'boluwaduro', label: 'Boluwaduro' },
    { value: 'boripe', label: 'Boripe' },
    { value: 'ede_north', label: 'Ede North' },
    { value: 'ede_south', label: 'Ede South' },
    { value: 'egbedore', label: 'Egbedore' },
    { value: 'ejigbo', label: 'Ejigbo' },
    { value: 'ife_central', label: 'Ife Central' },
    { value: 'ife_east', label: 'Ife East' },
    { value: 'ife_north', label: 'Ife North' },
    { value: 'ife_south', label: 'Ife South' },
    { value: 'ifedayo', label: 'Ifedayo' },
    { value: 'ifelodun_osun', label: 'Ifelodun' },
    { value: 'ila', label: 'Ila' },
    { value: 'ilesa_east', label: 'Ilesa East' },
    { value: 'ilesa_west', label: 'Ilesa West' },
    { value: 'irepodun_osun', label: 'Irepodun' },
    { value: 'irewole', label: 'Irewole' },
    { value: 'isokan', label: 'Isokan' },
    { value: 'iwo', label: 'Iwo' },
    { value: 'obokun', label: 'Obokun' },
    { value: 'odo_otin', label: 'Odo Otin' },
    { value: 'ola_oluwa', label: 'Ola Oluwa' },
    { value: 'olorunda', label: 'Olorunda' },
    { value: 'oriade', label: 'Oriade' },
    { value: 'orolu', label: 'Orolu' },
    { value: 'osogbo', label: 'Osogbo' },
  ],
  oyo: [
    { value: 'afijio', label: 'Afijio' },
    { value: 'akinyele', label: 'Akinyele' },
    { value: 'atiba', label: 'Atiba' },
    { value: 'atisbo', label: 'Atisbo' },
    { value: 'egbeda', label: 'Egbeda' },
    { value: 'ibadan_north', label: 'Ibadan North' },
    { value: 'ibadan_north_east', label: 'Ibadan North-East' },
    { value: 'ibadan_north_west', label: 'Ibadan North-West' },
    { value: 'ibadan_south_east', label: 'Ibadan South-East' },
    { value: 'ibadan_south_west', label: 'Ibadan South-West' },
    { value: 'ibarapa_central', label: 'Ibarapa Central' },
    { value: 'ibarapa_east', label: 'Ibarapa East' },
    { value: 'ibarapa_north', label: 'Ibarapa North' },
    { value: 'ido', label: 'Ido' },
    { value: 'irepo', label: 'Irepo' },
    { value: 'iseyin', label: 'Iseyin' },
    { value: 'itesiwaju', label: 'Itesiwaju' },
    { value: 'iwajowa', label: 'Iwajowa' },
    { value: 'kajola', label: 'Kajola' },
    { value: 'lagelu', label: 'Lagelu' },
    { value: 'ogbomosho_north', label: 'Ogbomosho North' },
    { value: 'ogbomosho_south', label: 'Ogbomosho South' },
    { value: 'ogo_oluwa', label: 'Ogo Oluwa' },
    { value: 'olorunsogo', label: 'Olorunsogo' },
    { value: 'oluyole', label: 'Oluyole' },
    { value: 'ona_ara', label: 'Ona Ara' },
    { value: 'orelope', label: 'Orelope' },
    { value: 'ori_ire', label: 'Ori Ire' },
    { value: 'oyo_east', label: 'Oyo East' },
    { value: 'oyo_west', label: 'Oyo West' },
    { value: 'saki_east', label: 'Saki East' },
    { value: 'saki_west', label: 'Saki West' },
    { value: 'surulere_oyo', label: 'Surulere' },
  ],
  plateau: [
    { value: 'barkin_ladi', label: 'Barkin Ladi' },
    { value: 'bassa', label: 'Bassa' },
    { value: 'bokkos', label: 'Bokkos' },
    { value: 'jos_east', label: 'Jos East' },
    { value: 'jos_north', label: 'Jos North' },
    { value: 'jos_south', label: 'Jos South' },
    { value: 'kanam', label: 'Kanam' },
    { value: 'kanke', label: 'Kanke' },
    { value: 'langtang_north', label: 'Langtang North' },
    { value: 'langtang_south', label: 'Langtang South' },
    { value: 'mangu', label: 'Mangu' },
    { value: 'mikang', label: 'Mikang' },
    { value: 'pankshin', label: 'Pankshin' },
    { value: 'qua_an_pan', label: "Qua'an Pan" },
    { value: 'riyom', label: 'Riyom' },
    { value: 'shendam', label: 'Shendam' },
    { value: 'wase', label: 'Wase' },
  ],
  rivers: [
    { value: 'abua_odual', label: 'Abua/Odual' },
    { value: 'ahoada_east', label: 'Ahoada East' },
    { value: 'ahoada_west', label: 'Ahoada West' },
    { value: 'akuku_toru', label: 'Akuku-Toru' },
    { value: 'andoni', label: 'Andoni' },
    { value: 'asari_toru', label: 'Asari-Toru' },
    { value: 'bonny', label: 'Bonny' },
    { value: 'degema', label: 'Degema' },
    { value: 'eleme', label: 'Eleme' },
    { value: 'emohua', label: 'Emohua' },
    { value: 'etche', label: 'Etche' },
    { value: 'gokana', label: 'Gokana' },
    { value: 'ikwerre', label: 'Ikwerre' },
    { value: 'khana', label: 'Khana' },
    { value: 'obio_akpor', label: 'Obio/Akpor' },
    { value: 'ogba_egbema_ndoni', label: 'Ogba/Egbema/Ndoni' },
    { value: 'ogu_bolo', label: 'Ogu/Bolo' },
    { value: 'okrika', label: 'Okrika' },
    { value: 'omuma', label: 'Omuma' },
    { value: 'opobo_nkoro', label: 'Opobo/Nkoro' },
    { value: 'oyigbo', label: 'Oyigbo' },
    { value: 'port_harcourt', label: 'Port Harcourt' },
    { value: 'tai', label: 'Tai' },
  ],
  sokoto: [
    { value: 'binji', label: 'Binji' },
    { value: 'bodinga', label: 'Bodinga' },
    { value: 'dange_shuni', label: 'Dange Shuni' },
    { value: 'gada', label: 'Gada' },
    { value: 'goronyo', label: 'Goronyo' },
    { value: 'gudu', label: 'Gudu' },
    { value: 'gwadabawa', label: 'Gwadabawa' },
    { value: 'illela', label: 'Illela' },
    { value: 'isa', label: 'Isa' },
    { value: 'kebbe', label: 'Kebbe' },
    { value: 'kware', label: 'Kware' },
    { value: 'rabah', label: 'Rabah' },
    { value: 'sabon_birni', label: 'Sabon Birni' },
    { value: 'shagari', label: 'Shagari' },
    { value: 'silame', label: 'Silame' },
    { value: 'sokoto_north', label: 'Sokoto North' },
    { value: 'sokoto_south', label: 'Sokoto South' },
    { value: 'tambuwal', label: 'Tambuwal' },
    { value: 'tangaza', label: 'Tangaza' },
    { value: 'tureta', label: 'Tureta' },
    { value: 'wamako', label: 'Wamako' },
    { value: 'wurno', label: 'Wurno' },
    { value: 'yabo', label: 'Yabo' },
  ],
  taraba: [
    { value: 'ardo_kola', label: 'Ardo Kola' },
    { value: 'bali', label: 'Bali' },
    { value: 'donga', label: 'Donga' },
    { value: 'gashaka', label: 'Gashaka' },
    { value: 'gassol', label: 'Gassol' },
    { value: 'ibi', label: 'Ibi' },
    { value: 'jalingo', label: 'Jalingo' },
    { value: 'karim_lamido', label: 'Karim Lamido' },
    { value: 'kumi', label: 'Kumi' },
    { value: 'lau', label: 'Lau' },
    { value: 'sardauna', label: 'Sardauna' },
    { value: 'takum', label: 'Takum' },
    { value: 'ussa', label: 'Ussa' },
    { value: 'wukari', label: 'Wukari' },
    { value: 'yorro', label: 'Yorro' },
    { value: 'zing', label: 'Zing' },
  ],
  yobe: [
    { value: 'bade', label: 'Bade' },
    { value: 'bursari', label: 'Bursari' },
    { value: 'damaturu', label: 'Damaturu' },
    { value: 'fika', label: 'Fika' },
    { value: 'fune', label: 'Fune' },
    { value: 'geidam', label: 'Geidam' },
    { value: 'gujba', label: 'Gujba' },
    { value: 'gulani', label: 'Gulani' },
    { value: 'jakusko', label: 'Jakusko' },
    { value: 'karasuwa', label: 'Karasuwa' },
    { value: 'machina', label: 'Machina' },
    { value: 'nangere', label: 'Nangere' },
    { value: 'nguru', label: 'Nguru' },
    { value: 'potiskum', label: 'Potiskum' },
    { value: 'tarmuwa', label: 'Tarmuwa' },
    { value: 'yunusari', label: 'Yunusari' },
    { value: 'yusufari', label: 'Yusufari' },
  ],
  zamfara: [
    { value: 'anka', label: 'Anka' },
    { value: 'bakura', label: 'Bakura' },
    { value: 'birnin_magaji_kiyaw', label: 'Birnin Magaji/Kiyaw' },
    { value: 'bukkuyum', label: 'Bukkuyum' },
    { value: 'bungudu', label: 'Bungudu' },
    { value: 'gummi', label: 'Gummi' },
    { value: 'gusau', label: 'Gusau' },
    { value: 'kaura_namoda', label: 'Kaura Namoda' },
    { value: 'maradun', label: 'Maradun' },
    { value: 'maru', label: 'Maru' },
    { value: 'shinkafi', label: 'Shinkafi' },
    { value: 'talata_mafara', label: 'Talata Mafara' },
    { value: 'tsafe', label: 'Tsafe' },
    { value: 'zurmi', label: 'Zurmi' },
  ],
}
